 -- Dockerfile Example --

RUN - executes only inside the environment
COMMAND - executes outside of the environment when we specify. 
ENTRYPOINT - executes a call from outside the environment to run inside the environment

--------------------------------------------------


FROM mcr.microsoft.com/dotnet/core/sdk as build (download the whole dotnet sdk)
WORKDIR /aspnet     (this is your working directory)
COPY . /aspnet      (copy everything in our current directory to the working directory)
RUN dotnet build
RUN dotnet publish --no-restore -c Release -o out 

FROM mcr.microsoft.com/dotnet/core/aspnet (download just the runtime from the dotnet sdk)
WORKDIR /dist
COPY --from=build /aspnet/out .
CMD [ "dotnet", "Devops.Client.dll" ]